What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array
object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays,
including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic
statistical operations, random simulation and much more.

In [ ]:
import numpy as np  #importing numpy library for numerical operations


# 1D array # Vector
a = np.array([1, 2, 3])  #creating a numpy array with elements 1, 2, and 3

#### Vector

In [ ]:
print(type(a))  #checking the type of variable 'a' to confirm it's a numpy array
print(a)  #printing the contents of the array 'a'

<class 'numpy.ndarray'>
[1 2 3]


Above arr is 1D arr and can be said as Vector

### Matrix

In [7]:
# 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])  #creating a 2D numpy array with two rows and three columns
b

array([[1, 2, 3],
       [4, 5, 6]])

Above b array can be said as a matrix as it is 2D arr

#### TenSor

In [6]:
# Multi-dimensional array
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  #creating a  3D numpy array with two blocks, each containing two rows and two columns
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Above arr is multidim so it is said to be as Tensor 

In [8]:
#np.arange  #creating a numpy array with a range of values

In [9]:
#np.reshape  #checking the shape of a numpy array
np.arange(10).reshape(2, 5)  #creating a numpy array with a range of values and reshaping it into a 2x5 array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
np.arange(10).reshape(5, 2)  #creating a numpy array with a range of values and reshaping it into a 5x2 array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [11]:
#np.ones((3, 4))  #creating a 3x4 array filled with ones
#Syntax: np.ones(shape, dtype=None, order='C')
#shape: A tuple representing the dimensions of the array (e.g., (3, 4) for a 3x4 array).

np.ones((3, 4))  #creating a 3x4 array filled with ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.zeros((2, 3))  #creating a 2x3 array filled with zeros


array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
#np.random.rand(3, 4)  #generating a 3x4 array of random numbers between 0 and 1
np.random.rand(3, 4)  #generating a 3x4 array of random numbers between 0 and 1

array([[0.01351199, 0.88046948, 0.20176099, 0.49953558],
       [0.94883208, 0.69829264, 0.97848545, 0.50132569],
       [0.83568075, 0.79989034, 0.72902661, 0.06323115]])

In [14]:
#np.linspace(0, 1, 5)  #generating an array of 5 evenly spaced numbers between 0 and 1 #linear space
#Syntax: np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
np.linspace(-10, 10, 5 , dtype=int)  #generating an array of 5 evenly distributed numbers between -10 and 10 #linear space

array([-10,  -5,   0,   5,  10])

In [15]:
#np.identity(a)  #checking the memory address of the array 'a'
#Syntax: np.identity(n, dtype=None)
np.identity(5)  #creating a 5x5 identity matrix having 1s on the diagonal and 0s elsewhere


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Array Attributes

In [17]:
a1 = np.arange(1, 10)  #Vector
a2 = np.arange(12, dtype=float).reshape(3,4)  #Matrix
a3 = np.arange(24).reshape(2, 3, 4)  #Tensor

In [18]:
print("Vector a1:\n", a1)  #printing the 1D array (vector)
print()
print("Matrix a2:\n", a2) #printing the 2D array (matrix)  
print()
print("Tensor a3:\n", a3)  #printing the 3D array (tensor)

Vector a1:
 [1 2 3 4 5 6 7 8 9]

Matrix a2:
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

Tensor a3:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [19]:
#ndim  #checking the number of dimensions of a numpy array
print("Number of dimensions in a1:", a1.ndim)  #checking the number
print("Number of dimensions in a2:", a2.ndim)  #checking the number of dimensions in the 2D array (matrix)
print("Number of dimensions in a3:", a3.ndim)  #checking the number of dimensions in the 3D array (tensor)

Number of dimensions in a1: 1
Number of dimensions in a2: 2
Number of dimensions in a3: 3


In [20]:
#shape  #checking the shape of a numpy array
print("Shape of a1:", a1.shape)  #checking the shape of the 1D array (vector)
print("Shape of a2:", a2.shape)  #checking the shape of the 2D array (matrix)
print("Shape of a3:", a3.shape)  #checking the shape of the 3D array (tensor)


Shape of a1: (9,)
Shape of a2: (3, 4)
Shape of a3: (2, 3, 4)


### Changing DType

In [21]:
#astype
print(a3.dtype)
a3.astype(np.int32)


int64


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]], dtype=int32)

### Array Operation


In [23]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

##### Scaler Operations

In [26]:
# Scaler Operations
# arithmatic

a2 + 2

# also Subtraction ,Divsion , multiplictn, Modulo

array([[14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [28]:
# Relational Operations

a2 % 2 == 0 #those with  even only


array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

### Vector OPeration i] Arithmatic    ii] Relational


In [29]:
# Two Vector Addition 
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [43]:
a1 = np.arange(12).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Array Functions For Mathematical operations in numpy

In [50]:
# Numpy Functions are as follows:
# np.sum()  #calculating the sum of all elements in an array 
# np.mean()  #calculating the mean of all elements in an array
a1.mean()
# np.median()  #calculating the median of all elements in an array
# np.std()  #calculating the standard deviation of all elements in an array
# np.min()  #finding the minimum value in an array
# np.max()  #finding the maximum value in an array
# np.argmin()  #finding the index of the minimum value in an array
# np.argmax()  #finding the index of the maximum value in an array
# np.unique()  #finding the unique elements in an array
# np.sort()  #sorting the elements of an array
# np.reshape()  #reshaping an array to a new shape
# np.transpose()  #transposing the dimensions of an array
a1.transpose()

# np.dot()  #performing dot product of two arrays
# np.linalg.inv()  #calculating the inverse of a matrix
# np.linalg.det()  #calculating the determinant of a matrix
# np.linalg.eig()  #calculating the eigenvalues and eigenvectors of a matrix

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [51]:
np.prod(a1)

np.int64(0)

In [54]:
np.sum(a1 , axis=0)  # axis 0 --> rowswise      axis 1 --> colswise

array([12, 15, 18, 21])

In [ ]:
np.sum(a1, axis= 1)

array([ 6, 22, 38])

## Indexing and slicing in no Array


In [57]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [61]:
# Accessing the element in a linear array  ie vector
a1
a1[-1]

np.int64(9)

In [ ]:
#Accessing the element in a 2D array  #a2[row, col]
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [66]:
print(a2[1, 1] )
print(a2[1,2])

5
6


In [71]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [72]:
#Accessing the element in a 3D array  #a3[m1[index], m2[index], a3[matrix]]
a3[1,1,0]

np.int64(6)

### Slicing

In [81]:
# Slin=cing in linear arr
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
a1[1:7]  #Syntax :   arr[start:end+1]  

array([1, 2, 3, 4, 5, 6])

In [77]:
a1[::2]

array([0, 2, 4, 6, 8])

Slicing in matrix

In [78]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [100]:
# access 2nd row from above 2D arr

print(a2[1:2],"\n")

#acccess 3rd col from above 2D arr

print(a2[::, 2:3])

print()
#accesss 4th col from above 2D arr

print(a2[:: , 3:])

[[4 5 6 7]] 

[[ 2]
 [ 6]
 [10]]

[[ 3]
 [ 7]
 [11]]


In [105]:
# access corner elements from 2D array matrix

print(a2[::2, ::3])


[[ 0  3]
 [ 8 11]]


### Slicing in (Tensor) 3D Array 

In [109]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [110]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [112]:
a3[::2] # 1st and 3rd matrics of tensor

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [113]:
## access middle col of 2nd matrix
a3[1,:, 1]

array([10, 13, 16])

In [114]:
# access last 4 corner elements of last matrix

a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [22]:
#Importing numpy functions are as follows:
#np.arange
#np.shape
#np.random.rand
#np.linspace
#np.identity
#These functions are commonly used for creating arrays, checking their properties, and generating random numbers in numpy.

#np.arange(start, stop, step)  #creates an array of evenly spaced values within a given interval
#np.shape(array)  #returns the dimensions of the array  
#np.random.rand(d0, d1, ..., dn)  #generates an array of random numbers between 0 and 1 with the specified shape
#np.linspace(start, stop, num)  #generates an array of evenly spaced numbers between start and stop
#np.identity(n)  #returns the identity array of size n x n  

In [ ]:
# Numpy Array Operations are as follows:
# np.add()  #element-wise addition of two arrays
# np.subtract()  #element-wise subtraction of two arrays
# np.multiply()  #element-wise multiplication of two arrays
# np.divide()  #element-wise division of two arrays
# np.power()  #element-wise exponentiation of an array
# np.sqrt()  #element-wise square root of an array
# np.exp()  #element-wise exponential of an array
# np.log()  #element-wise natural logarithm of an array
# np.sin()  #element-wise sine of an array
# np.cos()  #element-wise cosine of an array
# np.tan()  #element-wise tangent of an array
# np.arcsin()  #element-wise arcsine of an array
# np.arccos()  #element-wise arccosine of an array
# np.arctan()  #element-wise arctangent of an array
# np.sinh()  #element-wise hyperbolic sine of an array
# np.cosh()  #element-wise hyperbolic cosine of an array
# np.tanh()  #element-wise hyperbolic tangent of an array


In [ ]:
# numpy functions required for data science are as follows:
# np.mean()  #calculating the mean of a dataset 
# np.median()  #calculating the median of a dataset
# np.std()  #calculating the standard deviation of a dataset
# np.var()  #calculating the variance of a dataset
# np.corrcoef()  #calculating the correlation coefficient between two datasets
# np.histogram()  #calculating the histogram of a dataset
# np.percentile()  #calculating the percentile of a dataset
# These functions are commonly used in data science for analyzing and summarizing datasets, as well as for performing statistical calculations and visualizations.


### Iterating over arrays

#### 1D arr

In [117]:
for i in a1:
    print((i))

0
1
2
3
4
5
6
7
8
9


#### 2D array

In [118]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


### 3D Array (Tensor)

In [121]:
for i in a3:
    print(i)
    print()

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]

[[18 19 20]
 [21 22 23]
 [24 25 26]]



In [ ]:
for i in np.nditer(a3):   #if want to iterate throuhgh each element in Tensor
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [ ]:
l = a3.ravel() # if you want to convert multiidim to oneDim arr 
l

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking in arrays

In [ ]:
# np.hstack((__arrays__))  #it helps 
# np.vstack((__arrays__))



### Splitting in arrays

In [132]:
# np.hsplit((__arrays_, number of parts))
# np.vsplit((__arrays_, number of parts))